version: '3'
services:
    app:
      container_name: vaultwarden
      image: vaultwarden/server:latest
      restart: unless-stopped
      ports:
        - 8080:80
      volumes:
        - /configs/vaultwarden:/data
      network_mode: host