version: "2.1"
services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Central
    volumes:
      - /configs/fileshare/:/config
      - /oldlib/share/:/data
    ports:
      - 6443:443
    restart: unless-stopped
