version: "2.1"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /configs/jellyfin:/config
      - /library/data/media/tv:/tv
      - /library/data/media/movies:/movies
    ports:
      - 8096:8096
      - 7359:7359/udp #optional
    restart: unless-stopped